In [4]:
import logging

In [5]:
logging.critical("测试信息")

CRITICAL:root:测试信息


In [6]:
print("打印信息")

打印信息


In [7]:
print("debug",logging.DEBUG)

debug 10


In [8]:
logger=logging.getLogger("test")
logger.setLevel(logging.debug)


TypeError: Level not an integer or a valid string: <function debug at 0x0000022D5B4C8D60>

In [ ]:
logger.debug("debug")

In [ ]:
logger.error("error")

ERROR:test:error


In [2]:
import numpy as np


In [10]:
_array=np({1,2,3,4})

TypeError: 'module' object is not callable

In [5]:
array1=np.array(10)

In [7]:
array2=np.arange(1,2,20)

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.random.rand(3)

array([0.33982451, 0.09796494, 0.92742778])

In [11]:
arr=np.array({1,1,1})

In [12]:
arr.size


1

In [13]:
arr.shape

()

In [15]:
arrj=np.arange(20)

In [16]:
arrj

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
arrj[1:4]

array([1, 2, 3])